import { useState } from "react";
import { MainLayout } from "@/components/layout/MainLayout";
import { PageHeader } from "@/components/ui/PageHeader";
import { GenerateButton } from "@/components/ui/GenerateButton";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { FileText, Copy, Check } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

const contentTypes = [
  { value: "script", label: "Video Script" },
  { value: "article", label: "Blog Article" },
  { value: "social", label: "Social Media Post" },
  { value: "story", label: "Creative Story" },
  { value: "product", label: "Product Description" },
];

const tones = [
  { value: "professional", label: "Professional" },
  { value: "casual", label: "Casual" },
  { value: "funny", label: "Funny" },
  { value: "inspirational", label: "Inspirational" },
  { value: "educational", label: "Educational" },
];

const TextGenerator = () => {
  const [prompt, setPrompt] = useState("");
  const [contentType, setContentType] = useState("script");
  const [tone, setTone] = useState("professional");
  const [generatedText, setGeneratedText] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      toast({
        title: "Please enter a prompt",
        description: "Describe what you want to generate",
        variant: "destructive",
      });
      return;
    }

    setIsLoading(true);
    // Simulated generation
    await new Promise((resolve) => setTimeout(resolve, 2000));
    
    const sampleOutput = `# ${prompt}\n\nThis is a sample ${contentType} generated with a ${tone} tone.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.\n\n## Key Points\n\n1. First important point about ${prompt}\n2. Second crucial aspect to consider\n3. Final thoughts and recommendations\n\nThis content was generated by AI Studio to help you create engaging content quickly.`;
    
    setGeneratedText(sampleOutput);
    setIsLoading(false);
    toast({
      title: "Content generated!",
      description: "Your text has been created successfully",
    });
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    toast({
      title: "Copied to clipboard",
      description: "The generated text has been copied",
    });
  };

  return (
    <MainLayout>
      <PageHeader
        icon={FileText}
        title="Text Generator"
        description="Create scripts, articles, and creative content with AI"
      />

      <div className="grid gap-8 lg:grid-cols-2">
        {/* Input Section */}
        <div className="space-y-6 animate-fade-in" style={{ animationDelay: "0.1s" }}>
          <div className="glass-card rounded-xl p-6">
            <div className="space-y-4">
              <div>
                <Label htmlFor="prompt" className="text-sm font-medium text-foreground">
                  Describe your content
                </Label>
                <Textarea
                  id="prompt"
                  placeholder="E.g., Write a script about the benefits of meditation for beginners..."
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  className="mt-2 min-h-[120px] resize-none border-border bg-secondary/50 text-foreground placeholder:text-muted-foreground focus:border-primary"
                />
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <Label className="text-sm font-medium text-foreground">Content Type</Label>
                  <Select value={contentType} onValueChange={setContentType}>
                    <SelectTrigger className="mt-2 border-border bg-secondary/50">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {contentTypes.map((type) => (
                        <SelectItem key={type.value} value={type.value}>
                          {type.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label className="text-sm font-medium text-foreground">Tone</Label>
                  <Select value={tone} onValueChange={setTone}>
                    <SelectTrigger className="mt-2 border-border bg-secondary/50">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {tones.map((t) => (
                        <SelectItem key={t.value} value={t.value}>
                          {t.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <GenerateButton
                onClick={handleGenerate}
                isLoading={isLoading}
                disabled={!prompt.trim()}
                className="w-full"
              >
                Generate Text
              </GenerateButton>
            </div>
          </div>
        </div>

        {/* Output Section */}
        <div className="animate-fade-in" style={{ animationDelay: "0.2s" }}>
          <div className="glass-card h-full rounded-xl p-6">
            <div className="mb-4 flex items-center justify-between">
              <Label className="text-sm font-medium text-foreground">Generated Content</Label>
              {generatedText && (
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1.5 rounded-md px-2 py-1 text-xs text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
                >
                  {copied ? (
                    <>
                      <Check className="h-3.5 w-3.5" />
                      Copied
                    </>
                  ) : (
                    <>
                      <Copy className="h-3.5 w-3.5" />
                      Copy
                    </>
                  )}
                </button>
              )}
            </div>
            <div className="min-h-[300px] rounded-lg border border-border bg-secondary/30 p-4">
              {generatedText ? (
                <pre className="whitespace-pre-wrap font-sans text-sm text-foreground">
                  {generatedText}
                </pre>
              ) : (
                <p className="text-center text-sm text-muted-foreground">
                  Your generated content will appear here
                </p>
              )}
            </div>
          </div>
        </div>
      </div>
    </MainLayout>
  );
};

export default TextGenerator;
