// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdlssuosmuoeyrfbcnru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbHNzdW9zbXVvZXlyZmJjbnJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNjc2MjMsImV4cCI6MjA4NDc0MzYyM30.FEO9ecrj9IP3yP_k1fsVGR7lvVqqydBpevKfNp5NaPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});